docs: add example docs app using nextra
noaignite/accelerator pull request #243
Opened 2024-09-19 18:18 UTC by maeertin

2024-09-19 18:46 UTC, adamsoderstrom commented
_Great initiative, @maeertin!_

2024-09-20 14:37 UTC, adamsoderstrom commented on apps/docs/LICENSE
remove

2024-09-20 14:37 UTC, adamsoderstrom commented on apps/docs/src/pages/index.mdx
Rephrase

2024-09-20 14:37 UTC, adamsoderstrom commented on apps/docs/src/pages/about.mdx
Could probably be removed for now

2024-09-21 10:16 UTC, adamsoderstrom requested changes

2024-09-21 10:16 UTC, adamsoderstrom commented on docs/package.json
> +    "generate:markdown": "node --loader ts-node/esm --no-warnings=ExperimentalWarning ./scripts/generateMarkdown.ts",
**praise:** so nice!

2024-09-21 10:17 UTC, adamsoderstrom requested changes
Nice work, @maeertin !
Especially that we got automatic markdown generation from the JSDocs!

Though, one thing i think we should do move the `docs` directory into the `apps` directory.

A thought i have (non-blocking): Do we need to git track the generated Markdown files?

2024-09-23 14:40 UTC, adamsoderstrom approved these changes
We'll leave the documentation git-tracked for now.
If we stumble upon issues with lost documentation down the line, we'll take it then.

Good job! 🎉

2024-09-24 08:07 UTC, maeertin commented
> Nice work, @maeertin ! Especially that we got automatic markdown generation from the JSDocs!
> 
> Though, one thing i think we should do move the `docs` directory into the `apps` directory.
> 
> A thought i have (non-blocking): Do we need to git track the generated Markdown files?

Tracking the generated mdx files for now as one might want to add manually written mdx files alongside the generated ones. We can change this behaviour later on as you say.

2024-09-24 08:50 UTC, merged