feat(utils): add toggle helper
noaignite/accelerator pull request #324
Opened 2024-11-04 14:41 UTC by maeertin

2024-11-18 12:49 UTC, Dashice commented on packages/utils/src/toggle.ts
> +export function toggle<T>(array: T[], value: T): T[] {
- Should this be called `toggle`.
- Currently, item(s) previously toggled do not retain their index, should they?
- Should this work for Objects / Sets / Maps, how?
- Without passing references, you cannot toggle reference types; should you be able to?

2025-01-15 13:03 UTC, maeertin commented on packages/utils/src/toggle.ts
> +export function toggle<T>(array: T[], value: T): T[] {
> * Should this be called toggle?

It could be called something like `toggleArrayValue` instead. If so, there are some questions that come to mind. What are we reserving the name `toggle` for? And what is the difference between this naming versus for example the function `omit` which handles objects and is not called something like `omitObjectKey`?

> * Currently, item(s) previously toggled do not retain their index, should they?

I would prefer to not complicate this helper as it's current intended purpose is very straightforward. All it does is to toggle the existence of `value` from the `array` in it's current state passed as the first argument. A very pure function.

> * Should this work for Objects / Sets / Maps, how?

Perhaps that it would make sense for a `Set`, but not for `Object`s or `Map`s. Object-like structures already have their own dedicated helpers like `omit` and `pick`. I would rather not go the route of expanding `omit` to also receive arrays.

> * Without passing references, you cannot toggle reference types; should you be able to?

This could be a good addition. Although, I would rather see this helper added to the repo in it's simplest form as a first version. Adding this functionality thereafter would give us a very clear comparison if we think the added amount of code is worth it.

2025-02-17 09:57 UTC, Dashice commented on packages/utils/src/toggle.ts
> +export function toggle<T>(array: T[], value: T): T[] {
Change name to `toggleArrayValue`... Consider future implementation of a `toggle` super func that allows other array-like types to be passed. Approved.

2025-02-17 09:58 UTC, Dashice requested changes
https://github.com/noaignite/accelerator/pull/324/files#r1957941429

2025-02-25 08:45 UTC, maeertin commented on packages/utils/src/toggle.ts
> +export function toggle<T>(array: T[], value: T): T[] {
Sounds good, going ahead with this :)

2025-03-03 13:01 UTC, adamsoderstrom approved these changes

2025-03-03 13:04 UTC, merged